version: "3.8"

services:
  db:
    image: postgres
    container_name: "local_pgdb"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadminr_container"
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "Jaca#12345"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data:
